services:
  nextjs:
    image: doxa_plc:latest
    environment:
      - NODE_ENV=production
    labels:
      - 'traefik.enable=true'
      # Change the host url here
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.routers.doxa-app.rule=Host(`doxaplc.com`)'
      - 'traefik.http.services.doxa-app.loadbalancer.server.port=3000'
      - 'traefik.http.routers.doxa-app.entrypoints=websecure'
      - 'traefik.http.routers.doxa-app.tls=true'
      - 'traefik.http.routers.doxa-app.tls.certresolver=leresolver'

    deploy:
      replicas: 3
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
