services:
  nextjs:
    image: doxa_plc:latest
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.doxa_app.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.doxa_app.entrypoints=web
      - traefik.http.routers.doxa_app.middlewares=https-redirect
      - traefik.http.routers.doxa_app-secure.rule=Host(`${DOMAIN}`)

      - traefik.http.routers.doxa_app-secure.entrypoints=websecure
      - traefik.http.routers.doxa_app-secure.tls=true
      - traefik.http.routers.doxa_app-secure.tls.certresolver=le
      - traefik.http.routers.doxa_app-secure.service=project2-service
      - traefik.http.services.project2-service.loadbalancer.server.port=3000
    deploy:
      replicas: 3
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true