services:
  nextjs:
    image: doxa_plc:latest
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true

      - traefik.http.routers.project2-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.project2-http.entrypoints=http
      - traefik.http.routers.project2-http.middlewares=https-redirect
      - traefik.http.routers.project2-https.rule=Host(`${DOMAIN}`)

      - traefik.http.routers.project2-https.entrypoints=https
      - traefik.http.routers.project2-https.tls=true
      - traefik.http.routers.project2-https.tls.certresolver=le
      - traefik.http.routers.project2-https.service=project2-service
      - traefik.http.services.project2-service.loadbalancer.server.port=3000
    deploy:
      replicas: 3
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true