services:
  nextjs:
    image: doxa_plc:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.doxa_app.rule=Host(`doxaplc.com`)
        - traefik.http.routers.doxa_app.entrypoints=web
        - traefik.http.routers.doxa_app.middlewares=https-redirect

        - traefik.http.routers.doxa_app-secure.rule=Host(`doxaplc.com`)
        - traefik.http.routers.doxa_app-secure.entrypoints=websecure
        - traefik.http.routers.doxa_app-secure.tls=true
        - traefik.http.routers.doxa_app-secure.tls.certresolver=le
        - traefik.http.routers.doxa_app-secure.service=doxa_app-service
        - traefik.http.services.doxa_app-service.loadbalancer.server.port=3000

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
