/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    leads: Lead;
    visits: Visit;
    'consent-events': ConsentEvent;
    'team-members': TeamMember;
    projects: Project;
    'pricing-tiers': PricingTier;
    'add-ons': AddOn;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    visits: VisitsSelect<false> | VisitsSelect<true>;
    'consent-events': ConsentEventsSelect<false> | ConsentEventsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'pricing-tiers': PricingTiersSelect<false> | PricingTiersSelect<true>;
    'add-ons': AddOnsSelect<false> | AddOnsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and for when it fails to load.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  country?: string | null;
  projectType?:
    ('Website' | 'E-Commerce' | 'Custom Software' | 'Mobile App' | 'Branding' | 'Maintenance' | 'Other') | null;
  budget?: ('Under $2,000' | '$2,000 – $5,000' | '$5,000 – $10,000' | '$10,000+' | 'Not sure yet') | null;
  message: string;
  status?: ('new' | 'contacted' | 'quoted' | 'won' | 'lost') | null;
  notes?: string | null;
  visitorHash?: string | null;
  visitorId?: string | null;
  /**
   * How they first found the site.
   */
  firstTouch?: {
    channel?:
      ('Paid Search' | 'Paid Social' | 'Organic Search' | 'Organic Social' | 'Email' | 'Referral' | 'Direct') | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    gclid?: string | null;
    fbclid?: string | null;
    msclkid?: string | null;
    ttclid?: string | null;
    liFatId?: string | null;
    referrer?: string | null;
    referrerHost?: string | null;
    landingPath?: string | null;
  };
  /**
   * The session that produced the inquiry.
   */
  lastTouch?: {
    channel?:
      ('Paid Search' | 'Paid Social' | 'Organic Search' | 'Organic Social' | 'Email' | 'Referral' | 'Direct') | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    gclid?: string | null;
    fbclid?: string | null;
    msclkid?: string | null;
    ttclid?: string | null;
    liFatId?: string | null;
    referrer?: string | null;
    referrerHost?: string | null;
    landingPath?: string | null;
  };
  /**
   * From CDN headers, not the country they typed.
   */
  geoCountry?: string | null;
  /**
   * Internal 'new inquiry' email delivered.
   */
  notificationSent?: boolean | null;
  /**
   * Customer confirmation email delivered.
   */
  confirmationSent?: boolean | null;
  deliveryError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits".
 */
export interface Visit {
  id: number;
  visitorHash: string;
  /**
   * Set only with analytics consent.
   */
  visitorId?: string | null;
  channel?:
    ('Paid Search' | 'Paid Social' | 'Organic Search' | 'Organic Social' | 'Email' | 'Referral' | 'Direct') | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  gclid?: string | null;
  fbclid?: string | null;
  msclkid?: string | null;
  ttclid?: string | null;
  liFatId?: string | null;
  referrer?: string | null;
  referrerHost?: string | null;
  landingPath?: string | null;
  country?: string | null;
  deviceClass?: ('desktop' | 'mobile' | 'tablet' | 'bot') | null;
  /**
   * Analytics consent was granted at capture time.
   */
  consented?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-events".
 */
export interface ConsentEvent {
  id: number;
  visitorHash: string;
  visitorId?: string | null;
  analytics?: boolean | null;
  marketing?: boolean | null;
  policyVersion: string;
  action: 'accept-all' | 'reject-all' | 'custom' | 'withdrawn';
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Used as the React key and for future profile URLs.
   */
  slug: string;
  role: string;
  expertise?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  bio: string;
  /**
   * Absolute image URL, e.g. https://cdn.doxaplc.com/...
   */
  photo: string;
  social?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Shows this person in the Founders block rather than the team grid. An explicit flag, not a search for "Founder" in the role text, so retyping a job title cannot silently move someone between sections.
   */
  founder?: boolean | null;
  /**
   * Uncheck to hide without deleting.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL segment: /works/<slug>. Changing it breaks existing links.
   */
  slug: string;
  client: string;
  country: string;
  /**
   * ISO 3166-1 alpha-2, drives the flag. e.g. NL
   */
  countryCode: string;
  industry: string;
  summary: string;
  problem: string;
  approach?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  whatWeBuilt: string;
  /**
   * Optional. Filling this in also emits a Review into the page's structured data.
   */
  testimonial?: {
    quote?: string | null;
    name?: string | null;
    role?: string | null;
  };
  techStack?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty for in-house or unreleased work.
   */
  liveUrl?: string | null;
  logo: string;
  coverImage: string;
  /**
   * Optional. Falls back to the shared recommendations folder.
   */
  recommendationUrl?: string | null;
  featured?: boolean | null;
  status: 'live' | 'in-development';
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Uncheck to hide without deleting.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers".
 */
export interface PricingTier {
  id: number;
  name: string;
  bestFor: string;
  includes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Quote only shows "On request" and switches the button to booking a scoping call.
   */
  mode: 'from' | 'quote';
  /**
   * Number only, no symbol or commas. Ignored when quote only.
   */
  amountUsd?: number | null;
  /**
   * Shown to Ethiopian visitors. Ignored when quote only.
   */
  amountEtb?: number | null;
  timeline: string;
  /**
   * e.g. "30 / 40 / 30 milestones"
   */
  payment: string;
  /**
   * Draws the "Most Popular" treatment. Use on one tier.
   */
  highlighted?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "add-ons".
 */
export interface AddOn {
  id: number;
  name: string;
  detail: string;
  amountUsd: number;
  interval: 'month' | 'once';
  order: number;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'visits';
        value: number | Visit;
      } | null)
    | ({
        relationTo: 'consent-events';
        value: number | ConsentEvent;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'pricing-tiers';
        value: number | PricingTier;
      } | null)
    | ({
        relationTo: 'add-ons';
        value: number | AddOn;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  country?: T;
  projectType?: T;
  budget?: T;
  message?: T;
  status?: T;
  notes?: T;
  visitorHash?: T;
  visitorId?: T;
  firstTouch?:
    | T
    | {
        channel?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        gclid?: T;
        fbclid?: T;
        msclkid?: T;
        ttclid?: T;
        liFatId?: T;
        referrer?: T;
        referrerHost?: T;
        landingPath?: T;
      };
  lastTouch?:
    | T
    | {
        channel?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        gclid?: T;
        fbclid?: T;
        msclkid?: T;
        ttclid?: T;
        liFatId?: T;
        referrer?: T;
        referrerHost?: T;
        landingPath?: T;
      };
  geoCountry?: T;
  notificationSent?: T;
  confirmationSent?: T;
  deliveryError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits_select".
 */
export interface VisitsSelect<T extends boolean = true> {
  visitorHash?: T;
  visitorId?: T;
  channel?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  gclid?: T;
  fbclid?: T;
  msclkid?: T;
  ttclid?: T;
  liFatId?: T;
  referrer?: T;
  referrerHost?: T;
  landingPath?: T;
  country?: T;
  deviceClass?: T;
  consented?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-events_select".
 */
export interface ConsentEventsSelect<T extends boolean = true> {
  visitorHash?: T;
  visitorId?: T;
  analytics?: T;
  marketing?: T;
  policyVersion?: T;
  action?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  expertise?:
    | T
    | {
        value?: T;
        id?: T;
      };
  bio?: T;
  photo?: T;
  social?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  order?: T;
  founder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  country?: T;
  countryCode?: T;
  industry?: T;
  summary?: T;
  problem?: T;
  approach?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whatWeBuilt?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
      };
  techStack?:
    | T
    | {
        value?: T;
        id?: T;
      };
  liveUrl?: T;
  logo?: T;
  coverImage?: T;
  recommendationUrl?: T;
  featured?: T;
  status?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers_select".
 */
export interface PricingTiersSelect<T extends boolean = true> {
  name?: T;
  bestFor?: T;
  includes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  mode?: T;
  amountUsd?: T;
  amountEtb?: T;
  timeline?: T;
  payment?: T;
  highlighted?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "add-ons_select".
 */
export interface AddOnsSelect<T extends boolean = true> {
  name?: T;
  detail?: T;
  amountUsd?: T;
  interval?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email: string;
  /**
   * Primary number, shown with the WhatsApp link.
   */
  phone: string;
  /**
   * Secondary number. Footer only.
   */
  phone2?: string | null;
  /**
   * Digits only in international format, e.g. 251961412909. Used to build the wa.me link.
   */
  whatsapp: string;
  /**
   * Username without the @.
   */
  telegram: string;
  /**
   * Street line. The long address (contact and about pages) is street, city, region, country; the short one (footer) drops the street.
   */
  street: string;
  city: string;
  region: string;
  country: string;
  /**
   * ISO 3166-1 alpha-2, e.g. ET
   */
  countryCode: string;
  /**
   * Used only by LocalBusiness structured data.
   */
  latitude: number;
  longitude: number;
  /**
   * Short Google Maps link. This is what every address on the site links to.
   */
  mapUrl: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  phone2?: T;
  whatsapp?: T;
  telegram?: T;
  street?: T;
  city?: T;
  region?: T;
  country?: T;
  countryCode?: T;
  latitude?: T;
  longitude?: T;
  mapUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}